services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    volumes:
      - ./src:/app
      - ./indexes:/indexes
      - ./models:/app/models
      # - models:/tmp/llama_index
    ports:
      - "5000:5000"
    environment:
      MEDIAWIKI_URL: ${MEDIAWIKI_URL}
      MEDIAWIKI_API_URL: ${MEDIAWIKI_API_URL}
      MEDIAWIKI_NAMESPACES: ${MEDIAWIKI_NAMESPACES}
      MEDIAWIKI_USERNAME: ${W4R_MW_ADMIN_USER}
      MEDIAWIKI_USERPASS: ${MEDIAWIKI_USERPASS}
      MODEL_URL: ${MODEL_URL:-}
      MODEL_PATH: ${MODEL_PATH:-}
      MEDIAWIKI_APFROM: ${MEDIAWIKI_APFROM}
      MEDIAWIKI_APTO: ${MEDIAWIKI_APTO}
      ELASTICSEARCH_URL: ${W4R_LLM_ELASTICSEARCH_URL}
#      LOG_LEVEL: "DEBUG"

# volumes:
#   models: